has_aux_classifier: false
batch_size: 8
epochs: 1
image_size: 512
num_classes: 1
learning_rate: 0.0001
max_learning_rate: 0.0001
learning_rate_weight_decay: 0.1
ignore_index: 0
dataset: vitsegh
model: segformer
save_frequency: 1
num_dataloader_workers: 2
output_path: /home/ec2-user/SageMaker/output/
data_path: /home/ec2-user/SageMaker/data/downloads/
loss: tversky
lr_scheduler: plateau
weight_filepath: /home/ec2-user/SageMaker/pretrained_weights/segformer/citysemsegformer_mit.pth

